### ISSUE TITLE
Obj texture missing

### ISSUE THREAD

**Issue by stspanho** [shunsukesaito/PIFu#1]
Hi,

I'm trying to run the demo script. The mesh generation (obj file) works perfectly. How can I generate the texture or am I missing something?

The script also generates a png file, but that seems to be a screenshot?

![result_ryota](https://user-images.githubusercontent.com/5623789/75115870-127aa500-5663-11ea-8ac7-a12a9ad87b59.png)

Thank you

**Comment by shunsukesaito** [comment]
Which obj viewer are you using? Please open the generated mesh with meshlab to see if you can see the predicted texture. The predicted texture is assigned as per vertex color, not a texture map.

**Comment by stspanho** [comment]
Ok thank you it works!

**Comment by decajcd** [comment]
> Ok thank you it works!

Did the result you run in your own data?
