### ISSUE TITLE
How to do multi-view reconstruction using the pretrained models

### ISSUE THREAD

**Issue by Pushkar2307** [shunsukesaito/PIFu#12]
Hi,
Loved the paper. Thanks for releasing the code. 
I'm unable to do multi-view reconstruction using the pretrained models available. Can you help with the same?

**Comment by shunsukesaito** [comment]
Please refer to #3. The released model is not trained for multi-view setup and at this moment, we don't plan to release the model for multi-view or example codes (but the code base can be naturally extended to multi-view setup.)

**Comment by alitokur** [comment]
@Pushkar2307 hi, did you have any result for multi-view reconstruciton?
