### ISSUE TITLE
error cannot marching cubes

### ISSUE THREAD

**Issue by sinAshish** [shunsukesaito/PIFu#127]
Hi @shunsukesaito, thanks for sharing the code for this work.

I have prepared the renderings of my own dataset as per the mentioned data preparation steps.
But when I run the code for training shape/color, I get the error:
```
error cannot marching cubes
cannot unpack non-iterable int object
Can not create marching cubes at this time.
```
I know that this error might occur during the initial stages of training when the network has not learned properly, but in my case the error persists during the complete phase of training.

What do you think could be the reason for this? Or did I make any mistake during the creation of my dataset?

**Comment by Ranqing** [comment]
maybe you can check the version of skimage. In my situation, when i replace the marching_cube_lewiner by marching_cube, the error is fixed

**Comment by IHe-KaiI** [comment]
> maybe you can check the version of skimage. In my situation, when i replace the marching_cube_lewiner by marching_cube, the error is fixed

Hi, i wonder what's the version of your skimage and where is the marching_cube_lewiner to replace? Thanks!

**Comment by Jarvisss** [comment]
I meet the same problem and I check the predicted sdf, with values all 0, which means that all vertices are outside mesh, thus the threshold 0.5 fails to generate a surface. 
And I check my dataset and find that my meshes are not watertight, I'm trying to fill the holes and check if it works .

**Comment by bernakabadayi** [comment]
This fixed for me. https://githubhot.com/repo/facebookresearch/pifuhd/issues/149

**Comment by Yuhuoo** [comment]
> I meet the same problem and I check the predicted sdf, with values all 0, which means that all vertices are outside mesh, thus the threshold 0.5 fails to generate a surface. And I check my dataset and find that my meshes are not watertight, I'm trying to fill the holes and check if it works .
so, Have you fixd the problem now? I meet the same problem, and I use the THuman2.0 dataset

**Comment by Yuhuoo** [comment]
> I meet the same problem and I check the predicted sdf, with values all 0, which means that all vertices are outside mesh, thus the threshold 0.5 fails to generate a surface. And I check my dataset and find that my meshes are not watertight, I'm trying to fill the holes and check if it works .

so, Have you fixed the problem now? I meet the same problem.

**Comment by Jarvisss** [comment]
@Yuhuoo Yes, you may comment the try/catch to check where the error exactly occurs

**Comment by Yuhuoo** [comment]
> @Yuhuoo Yes, you may comment the try/catch to check where the error exactly occurs

Thank you for your replys, but I still don't know how to do. Can you describe shortly?

**Comment by Yuhuoo** [comment]
> @Yuhuoo Yes, you may comment the try/catch to check where the error exactly occurs

Thank you for your reply, but I still don't kown how to do. Can you share the code?

**Comment by raj-gupta1** [comment]
> Open PIFu/lib/mesh_util.py and change line 45 to 

**verts, faces, normals, values = measure.marching_cubes(sdf, 0.5)**


 It will work since marching_cubes_lewiner is depreciated.

**Comment by warmilk** [comment]
maybe you can check the version of skimage. In my situation, when i replace the **marching_cube_lewiner** by **marching_cubes**, the error is fixed

**Comment by warmilk** [comment]
scikit-image==0.19.3

venv/Lib/site-packages/skimage/measure/__init__.py

maybe you can check the version of skimage. In my situation, when i replace the marching_cube_lewiner by marching_cubes, the error is fixed

**Comment by IridescentJiang** [comment]
> > Open PIFu/lib/mesh_util.py and change line 45 to
> 
> **verts, faces, normals, values = measure.marching_cubes(sdf, 0.5)**
> 
> It will work since marching_cubes_lewiner is depreciated.

Thank you, this works for me!
