### ISSUE TITLE
Question about training data.

### ISSUE THREAD

**Issue by tyluann** [shunsukesaito/PIFu#14]

**Comment by tyluann** [comment]
Good work! I am trying to reproduce this. May I ask which datasets did you used for training? Are they free and public available? And if so, would you be so kind to share them?

**Comment by shunsukesaito** [comment]
We used about 500 scans from RenderPeople dataset. Unfortunately they are commercial scans and we are unable to share. Please refer to the appendix of https://arxiv.org/pdf/1905.05172.pdf for more detail on training data.

**Comment by tyluann** [comment]
Alrignt, thanks. BTW I have noticed that there is following work on CVPR2020. Would that paper be publiced online? I would be very interested to read that.

**Comment by shunsukesaito** [comment]
It will be online in a few days!

**Comment by shunsukesaito** [comment]
now it's up! https://shunsukesaito.github.io/PIFuHD/

**Comment by tyluann** [comment]
Thanks.

**Comment by wangfudong** [comment]
> We used about 500 scans from RenderPeople dataset. Unfortunately they are commercial scans and we are unable to share. Please refer to the appendix of https://arxiv.org/pdf/1905.05172.pdf for more detail on training data.

En.... If convenient, could you tell me how much do you pay for buying 500 models from RenderPeople? It is too expensive for me.
