### ISSUE TITLE
How to make the texture image?

### ISSUE THREAD

**Issue by zhwang-hzau** [shunsukesaito/PIFu#142]
Hi, in the free dataset demo: **'rp_dennis_posed_004_OBJ'** you provided, it provides a texture image **'rp_dennis_posed_004_dif_2k.jpg'** for training or testing, but **how can I generate a similar texture image from my own 3D samples** for training purposes? I would be very grateful if you could answer me!
like this image: 
![QQ图片20221009102113](https://user-images.githubusercontent.com/112077891/194734597-29138f9e-810e-46cc-b7fe-a59b7af33e1d.png)

**Comment by zyj-2000** [comment]
@zhwang-hzau Hi, I want to get the uv-map and texture too. How did you solve the problem?

**Comment by yangqinhui0423** [comment]
@zhwang-hzau @zyj-2000 Hello, I want to get the texture image too, can you share me how you solve the problem?
