### ISSUE TITLE
problem when i run prt_util 

### ISSUE THREAD

**Issue by 1aq-qa1** [shunsukesaito/PIFu#148]
When I executed prt, the program got stuck and looked at the memory usage and found that there was a lot of it. 
When I debug, I found that the program is stuck in this step, has anyone encountered it?

![uTools_1680871711913](https://user-images.githubusercontent.com/57577944/230611658-e19605d3-1d37-4d6d-87ee-0796f0d5a8fe.png)
![uTools_1680871694308](https://user-images.githubusercontent.com/57577944/230611666-398710b0-f197-42b8-98f9-1922765ac014.png)
![uTools_1680871677866](https://user-images.githubusercontent.com/57577944/230611668-e690f8c5-922e-4e24-8f24-2047087fafae.png)

**Comment by 1aq-qa1** [comment]
解决了，卸载pyembree和trimesh，然后再重新安装。
步骤：
1. pip uninstall pyembree
2. pip uninstall trimesh
3. pip install pyembree

**Comment by juanfraherrero** [comment]
Hi, i have the same issue. Trying to run the generating data example.

I tried reinstall dependencys, but no effect.

In collab run for 10 minutes and procees terminated okey but with no result.

In my local, (Linux, 16Gb RAM, No Cuda (as requirements not specify) conda, python3.8, and same dependencys in requirements) pass 30 minutes and nothing, still running in the same line calculating intersections!

Also try to reduce n to 2 or 5 but still nothing.

Do someone know how much time it should take? Cause maybe i have to left the process running all night¿?

Thanks in advance to anyone who answer!
