### ISSUE TITLE
freeglut (foo): failed to open display ''

### ISSUE THREAD

**Issue by electronicliujiang** [shunsukesaito/PIFu#15]
The data preprocessing part cannot be realized

**Comment by electronicliujiang** [comment]
Can you provide a more concise data pre-processing solution? I will report the above error here. I located it. The problem is with glutInit ().

**Comment by shunsukesaito** [comment]
Please elaborate (your environment, OS, how to reproduce the issue etc) so that I can specify the problem and help you resolve it.

**Comment by cathylacus** [comment]
> 数据预处理部分不能被实现

How did you solve this problem？

**Comment by cathylacus** [comment]
> Please elaborate (your environment, OS, how to reproduce the issue etc) so that I can specify the problem and help you resolve it.

My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?

**Comment by electronicliujiang** [comment]
> > 请详细说明（您的环境，操作系统，如何重现问题等），以便我指定问题并帮助您解决。
> 
> 我的环境是命令Linux，没有图形界面的服务器，因此我不能生成训练集吗？

My data preprocessing operation is implemented under VMWare virtual machine

**Comment by cathylacus** [comment]
> > > 请详细说明（您的环境，操作系统，如何重现问题等），以便我指定问题并帮助您解决。
> > 
> > 
> > 我的环境是命令Linux，没有图形界面的服务器，因此我不能生成训练集吗？
> 
> My data preprocessing operation is implemented under VMWare virtual machine

So can you generate these folders?I run it then reporting the errors stated in the title.
