### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by electronicliujiang** [shunsukesaito/PIFu#16]
![QQ图片20200406183047](https://user-images.githubusercontent.com/38310357/78549335-c3fd2080-7834-11ea-8ce7-aebff5bffe8b.png)

**Comment by electronicliujiang** [comment]
loadShader does not work, is there a more concise data pre-processing version

**Comment by electronicliujiang** [comment]
![QQ图片20200407091326](https://user-images.githubusercontent.com/38310357/78619471-1af40b80-78b0-11ea-8f50-c0b4bd7a5695.png)

**Comment by electronicliujiang** [comment]
![QQ图片20200407091326](https://user-images.githubusercontent.com/38310357/78619517-2810fa80-78b0-11ea-90ef-13223e33bf32.png)

**Comment by shunsukesaito** [comment]
I pushed EGL version of rendering which supports off-screen rendering with NVIDIA GPUs. This should address your problem.

**Comment by electronicliujiang** [comment]
Thank you for your reply. The two problems I opened have been solved. You can close them. Thank you very much!
