### ISSUE TITLE
Questions about texture and multiview

### ISSUE THREAD

**Issue by nvdomidi** [shunsukesaito/PIFu#17]
Hello shunsuke, I have 3 questions:

1. After running the code, a colored image like the input is saved. Is this a render of the reconstructed 3D shape or is it just a copy of the input image? 
2. The reconstructed objects I get are without material. Is there an option to save the color?
3. I cant seem to get the multiview part of the code to work. I set --num_views to the number of pictures I have but it gives errors with tensor sizes. 

Great work and thank you in advance!

**Comment by shunsukesaito** [comment]
> After running the code, a colored image like the input is saved. Is this a render of the reconstructed 3D shape or is it just a copy of the input image?

The image is just the visualization of input fed into the network. 

>The reconstructed objects I get are without material. Is there an option to save the color?

By default, the code generate colored obj files. As the color is assigned per vertex not as an form of texture map, I recommend checking the results with meshlab to make sure color is there.

>I cant seem to get the multiview part of the code to work. I set --num_views to the number of pictures I have but it gives errors with tensor sizes.

Please refer to #3. The released model is not trained for multi-view setup and at this moment, we don't plan to release the model for multi-view or example codes (but the code base can be naturally extended to multi-view setup.)

**Comment by nvdomidi** [comment]
thank you!
