### ISSUE TITLE
Restriction on input image size

### ISSUE THREAD

**Issue by usamahjundia** [shunsukesaito/PIFu#2]
Seems like there is a slight restriction on input image size. When i input an image with size not equal to 512 x 512 (could be smaller, could be larger), i got the 
`the size of tensor a (blablabla) must match the size of tensor b (blablabla) at non singleton dimension blablabla `

So is there a restriction for input shape?

**Comment by shunsukesaito** [comment]
The hourglass network expects the input resolution to be a multiple of 32 and the model is trained with 512 x 512. I recommend resizing images to 512 x 512. For other resolutions, I wouldn't expect any good results.

**Comment by usamahjundia** [comment]
i see, that clears things up, thanks!
