### ISSUE TITLE
Question about reconstructing half-body

### ISSUE THREAD

**Issue by youwei-kafuu** [shunsukesaito/PIFu#20]
Hi Shunsuke , Thanks for your great work!

I run some demo and found there will be some problems when reconstructing only upper body .It seems that it will judge the half body as the whole body.I'm wondering if there is some way to let PIFu fit the half body?

Thanks in advance!

**Comment by shunsukesaito** [comment]
As I never trained with upper body only, rescaling based on upper body segmentation would result in highly deviated inputs from the training data distribution. One solution is to write your own cropping function to roughly align the scale and location of upperbody with other full body training data. Nevertheless, the reconstruction is likely worse than those of full body images.

**Comment by youwei-kafuu** [comment]
Thanks!I'll have a try
