### ISSUE TITLE
Question about the unsmoothing generated volume mesh

### ISSUE THREAD

**Issue by utc1205** [shunsukesaito/PIFu#21]
very interesting idea in 3d reconstruction from single image.I want to apply it in my work, but I find the generated volume mesh doesn't smooth . Besides, I test the case you provide in code and that result is also coarse but not fine, especially face. Do you have any idea to improve the mesh quality?  Thank very much.

**Comment by shunsukesaito** [comment]
I'm not sure what you mean by not being smooth. I believe the reconstructions are generally smooth. It'd be helpful if you can share your "non-smooth" results for reference. 

Regarding fine details, please refer to my new work PIFuHD [(https://shunsukesaito.github.io/PIFuHD/), which addresses the lack of details in the original PIFu work.
