### ISSUE TITLE
Result's front and back problem

### ISSUE THREAD

**Issue by komjii2** [shunsukesaito/PIFu#24]
Hi, I'm Hyunwoo.
I am very interested in your research.
Using the pretrained model you provided, I pulled the results using my own input image.
But I found one problem here.
I often found the problem of not properly distinguishing the front and back of a person.
Can you tell me if there is an option in the code to fix that element?

**Comment by shunsukesaito** [comment]
Can you share any results I can look into?

**Comment by komjii2** [comment]
These are links to my results.

https://drive.google.com/file/d/1uYqumFHDTfI1F4hucSMCt08ihrvc9vlr/view?usp=sharing
https://drive.google.com/file/d/1kj-keJ0Ggyriga6xCpq7mk87e7mtoqom/view?usp=sharing

**Comment by shunsukesaito** [comment]
Thanks for sharing! There are a few possibilities.
1. Our training data does not have any subjects with glasses. This kind of deviation would cause confusion to the network. 
2. It seems that the input image has slightly dark illumination. We didn't add dark illumination in the training, so this would be another problem. I would recommend using well lit images for best performance.

**Comment by komjii2** [comment]
Thanks for the kind answer!

I thought it because my input image was dark, but I didn't think about the glasses!

It was a great help!

**Comment by decajcd** [comment]
> Thanks for the kind answer!
> 
> I thought it because my input image was dark, but I didn't think about the glasses!
> 
> It was a great help!

Have you solved?
