### ISSUE TITLE
@shunsukesaito  SMPL models for the obj files generated

### ISSUE THREAD

**Issue by PRAKHAR-bit** [shunsukesaito/PIFu#25]
@shunsukesaito  Hi, thanks for the wonderful work. Can you tell me a way that the obj file which I generated using your code, I can convert it to a SMPL model. I can create an SMPL model with the arbitary parameters but I cannot texture it like PIFu . So any way in which I can use PIFu to generate a textured SMPL model

**Comment by shunsukesaito** [comment]
There is no straightforward way to convert PIFu reconstructions to SMPL as PIFu uses a non-parametric volumetric representation. One hack would be to reconstruct PIFu, fit SMPL model using HMR or whatever off-the-shelf reconstruction methods and then use only the color inference module in PIFu to texture SMPL. However, as the surface of PIFu and SMPL are not perfectly aligned, texture reconstruction on SMPL might be dirty.

**Comment by PRAKHAR-bit** [comment]
@shunsukesaito Thanks for replying .Special thanks for suggesting me alternate ways. For now decided to use dense pose to generate texture maps for SMPL textures Densepose makes them easily from 2d images.
Waiting for PIFUhd. 
Regards.
