### ISSUE TITLE
BUFF data

### ISSUE THREAD

**Issue by jsaisagar** [shunsukesaito/PIFu#29]
Hi,

Thanks for the training code. May I know if we could train PIFu with BUFF data as this data is noisy and is not watertight? 

Thanks,

**Comment by shunsukesaito** [comment]
At least the training code in the repository doesn't work with non-watertight mesh as we need occupancy label. You may need to first convert raw mesh into watertight mesh.

**Comment by jsaisagar** [comment]
Thanks for the quick reply. Is there any good tool you suggest for the conversion? Also, can we expect the same results if trained on BUFF?

Thanks,

**Comment by shunsukesaito** [comment]
I think you need not only hole filling but also some noise removal. So you may need multiple tools for this task. I can think of [generalized winding number](https://libigl.github.io/) and [screened poisson reconstruction](http://www.meshlab.net/) for hole filling, but I don't know any off-the-shelf tools for removing outliers. Probably the only way is to do it manually...

As the clothing variation and illumination variation in BUFF are severely limited, reconstruction quality for various clothing types will be likely worse.
