### ISSUE TITLE
Data Generation

### ISSUE THREAD

**Issue by zyz-1998** [shunsukesaito/PIFu#30]
Regarding data generation, what are the points to pay attention to in the preparation of training data, or can you recommend some data sets for learning, thank you very much

**Comment by shunsukesaito** [comment]
Can you elaborate more on what you want to know? What kind of applications do you intend to use PIFu for? For clothed human digitization, I'd recommend reading PIFu's supplementation material and this code carefully.

**Comment by zyz-1998** [comment]
In this aspect of furniture, such as shapenetCoreV1, is it okay? I hope to further learn 3D reconstruction by running your code. Much appreciations if your could reply my question.

**Comment by shunsukesaito** [comment]
The obj files in ShapeNet are non-watertight. Thus, you need to first convert them into occupancy fields. Previously when I tested on ShapeNet, I used [this data](https://github.com/xiumingzhang/GenRe-ShapeHD#downloading-our-trained-models-and-training-data). But it'd be best to follow sampling strategy in the original PIFu to achieve highly detailed geometry.

**Comment by zyz-1998** [comment]
Thank you very much for your answer, which solves my question
