### ISSUE TITLE
Multi-views evaluation

### ISSUE THREAD

**Issue by waldstein94** [shunsukesaito/PIFu#31]
Hello, I have questions about the way of evaluation with multi-views inputs.

After reading your paper, I couldn't understand the procedure of evaluation with multi-view inputs.
For training phase with multi-views input, we know corresponding pixel (xi, noted in your paper) between images from different view point for a single point X on the 3d model. However, for test phase, we don't know any 3d information or the relation between images. So, how do I pick the set of xi for a single voxel in 3d occupancy field in test phase?  

I'm sorry to bother you if the answer could have been obtained from your paper.

**Comment by shunsukesaito** [comment]
PIFu assumes you have camera calibration between multiple images for both training and test time. So during test time, you just need to query 3D points X within predefined 3D bounding box, then using the camera matrices, you should be able to obtain pixel coordinate x as well as depth for X.

**Comment by waldstein94** [comment]
Oh, you mean we have to know the rotation degree of each image to obtain the camera matrices?
Because I want to apply your code with multi-views images from video data, I should know detailed process in evaluation. 
Also, I think the function of gen_mesh is only for single-view input. Is it right?

**Comment by shunsukesaito** [comment]
>Oh, you mean we have to know the rotation degree of each image to obtain the camera matrices?

In our camera setup, indeed only rotation angles are the changing variables. But generally speaking, you need to know scale, rotation matrix, and translation for weak perspective model.

>Also, I think the function of gen_mesh is only for single-view input. Is it right?

Correct. You need to modify the code to incorporate multiple images.

**Comment by alitokur** [comment]
@waldstein94 hi, did you modify the gen_mesh function?
