### ISSUE TITLE
some results

### ISSUE THREAD

**Issue by alitokur** [shunsukesaito/PIFu#33]
Dear Sir,
If possible can you check my results.
There is problem with my face 😄. Do i miss something?

![result](https://user-images.githubusercontent.com/20575896/85201984-fedb0480-b30b-11ea-976a-8e472c98a523.png)

and my inputs: 
![input](https://user-images.githubusercontent.com/20575896/85202131-ef0ff000-b30c-11ea-93eb-72899055eda3.png)

**Comment by shunsukesaito** [comment]
Looks like your legs are cut in the middle, resulting in larger body ratio inside image. As our released model is trained with full body images only, this kind of size discrepancy may cause inaccurate 3D reconstruction.

**Comment by alitokur** [comment]
Thank you sir. I will try with full body.

**Comment by decajcd** [comment]
> Thank you sir. I will try with full body.

Did you get better result?

**Comment by alitokur** [comment]
when I used my whole body, I still could not achieve perfect results. idk, but the problem may be my beard, or I may be ugly. I'm working on multi-view pifu.  maybe it can help me get better results.

**Comment by ChanYeongShin** [comment]
@alitokur Did you implement multi-view setup?
