### ISSUE TITLE
torch grid_sample takes input in range [-1,1]

### ISSUE THREAD

**Issue by AlleUndKalle** [shunsukesaito/PIFu#34]
Thanks for your awesome work!

Here in the `index()` function definition (https://github.com/shunsukesaito/PIFu/blob/master/lib/geometry.py#L8), it is written that `uv` parameter is in range [0,1]. However, in pytorch documentation (https://pytorch.org/docs/stable/nn.functional.html#grid-sample) it is noted as [-1,1]. 

Is this a bug or typo in writing of the function definition?

**Comment by leezhongguo** [comment]
I think it should be [-1,1].

**Comment by shunsukesaito** [comment]
Sorry, it should be [-1,1] and my comment in the code was just wrong. Code itself is working as expected.
