### ISSUE TITLE
Rendered images problem

### ISSUE THREAD

**Issue by Brawie** [shunsukesaito/PIFu#36]
Hello shunsuke, I tried the apps.render_data to process the 'rp_dennis_posed_004' sample, while the rendered images look like this:
![0_0_00](https://user-images.githubusercontent.com/31624178/85522064-bedf8e80-b637-11ea-818c-5ec62a602e7d.jpg)

![54_0_00](https://user-images.githubusercontent.com/31624178/85522325-1251dc80-b638-11ea-99f3-10a43d5f7b69.jpg)

I have no idea about this problem, can you give me some advice? Thank you!

**Comment by shunsukesaito** [comment]
Can you give me more info about your environment?

**Comment by shunsukesaito** [comment]
It seems that znear and zfar is wrongly set.

**Comment by shunsukesaito** [comment]
I just confirmed with ubuntu 18.04, the latest code works fine.

**Comment by Brawie** [comment]
I was using python2, my bad, what a stupid question...Everything works fine on python3, sorry for bothering you
