### ISSUE TITLE
multi-view pifu roadmap

### ISSUE THREAD

**Issue by alitokur** [shunsukesaito/PIFu#37]
dear sir, how can i extended the codebase to multi-view setup.

- [ ] modify the data loader

- [ ] check SurfaceClassifier arguments

What else should I do?

**Comment by shunsukesaito** [comment]
You may also need to also modify mesh generator code as well as error computation code in .lib/train_util.py.

**Comment by AIdeveloper-oz** [comment]
@alitokur Hi, did you find any solution for multiview execution?

**Comment by alitokur** [comment]
hi @AIdeveloper-oz , not yet, i'm still working on it
