### ISSUE TITLE
Data Generation 

### ISSUE THREAD

**Issue by alitokur** [shunsukesaito/PIFu#40]
Hi Sir,
When I run the following script, should I get any output?
`python -m apps.prt_util -i {path_to_rp_dennis_posed_004_OBJ}`
My first time I got `"Killed"` 
My second time I didn't get any error but progress bar remained zero.

![issue](https://user-images.githubusercontent.com/20575896/86180474-eac9ab00-bb34-11ea-9b86-4ba30828188b.png)
gpu: gtx1070

Thanks in advance.

**Comment by shunsukesaito** [comment]
If the code runs properly, you will get `./bounce/bounce0.txt` and `./bounce/face.npy` under {path_to_rp_dennis_posed_004_OBJ}. If you cannot find these, likely you don't set the folder path properly or don't have pyembree installed.

**Comment by alitokur** [comment]
Thank you sir, reinstall `pyembree` fixed the problem.
