### ISSUE TITLE
creating mask 

### ISSUE THREAD

**Issue by nandu749** [shunsukesaito/PIFu#43]
How to create black-white mask, any repo or tutorial available

**Comment by shunsukesaito** [comment]
You can use any off the shelf systems such as remove.bg

**Comment by alitokur** [comment]
first of all;
1-) upload your image [right there](https://www.remove.bg/) and remove the background.
2-) download the image and move it into a folder you can easily access
3-) open terminal, 
`cd PIFu/apps`
4-) run the following code
`python crop_img.py -i /path/of/your/removedBackground/image -o /path/of/result`

**Comment by nandu749** [comment]
thank you, is there any better alternative for background subtraction(offline), tried mask rcnn, but not giving good results?

**Comment by shunsukesaito** [comment]
This is probably give you better segmentation than naive mask RCNN.
https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend
