### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by MC-E** [shunsukesaito/PIFu#47]
Sorry to bother you, I want to know how many  high-resolution photogrammetry scans from RenderPeople and BUFF needed to train this novel model. I try to train this model with only one photogrammetry scan from RenderPeople which is free to download and get a dissatisfied result.

**Comment by shunsukesaito** [comment]
BUFF is for evaluation only. We used about 460 scans from RenderPeople for training.

**Comment by MC-E** [comment]
OK, thanks for your reply!

**Comment by Brawie** [comment]
Hi shunsuke, may I ask which type of meshes from RenderPeople you used, the 'POSED' ones or the 'RIGGED' ones? Are there any other selecting rules or experiences?

**Comment by shunsukesaito** [comment]
This is the full set of training data. They are POSED model not RIGGED.
https://github.com/facebookresearch/pifuhd/blob/master/data/RenderPeople_all.csv
