### ISSUE TITLE
multiple index for each iteration

### ISSUE THREAD

**Issue by alitokur** [shunsukesaito/PIFu#51]
Dear Sir, I don't know why but here the _getitem_ function is called twice. (batch_size = 1 number_views = 1)

   ```
 for epoch in range(start_epoch, opt.num_epoch): #number of epoch is 100
        for train_idx, train_data in enumerate(train_data_loader): 
            iter_start_time = time.time()
            break
        break
```
ex:
epoch=0;
train_idx=0
the first iteration calls the _getitem_ 
i have two index here: they are 352 and 97.
but the index returned : 352. 
Is there any problem here or am I missing someting?

![Screenshot from 2020-07-16 21-31-37](https://user-images.githubusercontent.com/20575896/87708808-f6aba300-c7ab-11ea-9fb8-02e24085eb42.png)

**Comment by shunsukesaito** [comment]
what is your number of workers for data loader? Check if you have the same issue, when you set num_threads=0.

**Comment by alitokur** [comment]
huh! u are right, num_threads=0, fixed it.
