### ISSUE TITLE
Surface Classifier (y)

### ISSUE THREAD

**Issue by alitokur** [shunsukesaito/PIFu#53]
Dear Sir;
in single view PIFu if batch size is 1 the following are the tensor dimensions:
calib_tensor: 1, 4, 4
image_tensor: 1, 3, 512, 512
label_tensor: 1, 1, 5000
sample_tensor : 1, 3, 5000

And we send feature tensor the Surface Classifier. 
its size 1, 257, 5000 and SC returns y (1,1,5000)

but if we set number_views to 2 
calib_tensor: 2, 4, 4
image_tensor: 2, 3, 512, 512
label_tensor: 1, 1, 5000
sample_tensor : 2, 3, 5000
 
i guess everything is ok so far but new feature tensor : 2,257,5000 and SC returns 1,1,5000 again. Is this our problem in the Surface Classifier right?

**Comment by shunsukesaito** [comment]
Please read the code carefully. This is intended as multiview aggregation happens inside Surface Classifier.
