### ISSUE TITLE
Non-squared image resolution

### ISSUE THREAD

**Issue by faniry6** [shunsukesaito/PIFu#57]
I would like to train non-squared images datasets. Before going deeper into the coding, does it work for non-squared image? could you guide me which changes need to be done in case it does not? Of course, I could always apply some padding to my dataset to make it square but I will leave that as last option.

Thanks again.

**Comment by shunsukesaito** [comment]
Yes it does work for non-square images. However, please be aware that the width and height of an input image have to be multiple of 64 (4x downsampling before HG and 2^4x downsampling inside HG).

**Comment by faniry6** [comment]
Cool! thanks for the quick reply, I will check it out.
