### ISSUE TITLE
trian issue

### ISSUE THREAD

**Issue by jiandandian2** [shunsukesaito/PIFu#58]
hello, i used the training as your readme saying, and i test using the trained model : netG_epoch_99 and net_C_epoch_99, but it cannot work
![image](https://user-images.githubusercontent.com/33227739/89297381-50f6a000-d696-11ea-98f1-32da512e3acb.png)

**Comment by shunsukesaito** [comment]
Looks like your image filter of ResBlkPIFuNet during training and inference are not compatible. Please make sure you use the same model for both.

**Comment by Henry831** [comment]
I have a same problem,how can i get the model like your trained model?

**Comment by jiandandian2** [comment]
> I have a same problem,how can i get the model like your trained model?

I do as readme saying, data generation(step1 and step2 generate the standard dataset) and training(step1 output shape_weights, step2 output color weights)

**Comment by Henry831** [comment]
> > I have a same problem,how can i get the model like your trained model?
> 
> I do as readme saying, data generation(step1 and step2 generate the standard dataset) and training(step1 output shape_weights, step2 output color weights)

Yes,I have a same process like yours

**Comment by shunsukesaito** [comment]
Can you check if #61 solves your issue as well?

**Comment by jiandandian2** [comment]
> Can you check if #61 solves your issue as well?
it didn't , I train and test under the same environment...

**Comment by jiandandian2** [comment]
#61 sovled the problem
