### ISSUE TITLE
issue when eval with color net

### ISSUE THREAD

**Issue by troylujc** [shunsukesaito/PIFu#61]
Thank you for your great work. I trained the model with my own data. When I eval with only shape net, there is no problem. But when I eval with both net_G and net_C, errors occurred:
RuntimeError: Error(s) in loading state_dict for ResBlkPIFuNet:
	Missing key(s) in state_dict: "image_filter.model.2.weight", "image_filter.model.2.bias", "image_filter.model.5.weight", "image_filter.model.5.bias", "image_filter.model.8.weight", "image_filter.model.8.bias", "image_filter.model.10.conv_block.2.weight", "image_filter.model.10.conv_block.2.bias", "image_filter.model.10.conv_block.6.weight", "image_filter.model.10.conv_block.6.bias", "image_filter.model.11.conv_block.2.weight", "image_filter.model.11.conv_block.2.bias", "image_filter.model.11.conv_block.6.weight", "image_filter.model.11.conv_block.6.bias", "image_filter.model.12.conv_block.2.weight", "image_filter.model.12.conv_block.2.bias", "image_filter.model.12.conv_block.6.weight", "image_filter.model.12.conv_block.6.bias", "image_filter.model.13.conv_block.2.weight", "image_filter.model.13.conv_block.2.bias", "image_filter.model.13.conv_block.6.weight", "image_filter.model.13.conv_block.6.bias", "image_filter.model.14.conv_block.2.weight", "image_filter.model.14.conv_block.2.bias", "image_filter.model.14.conv_block.6.weight", "image_filter.model.14.conv_block.6.bias", "image_filter.model.15.conv_block.2.weight", "image_filter.model.15.conv_block.2.bias". 
	Unexpected key(s) in state_dict: "image_filter.model.1.bias", "image_filter.model.4.bias", "image_filter.model.7.bias", "image_filter.model.10.conv_block.1.bias", "image_filter.model.10.conv_block.5.bias", "image_filter.model.11.conv_block.1.bias", "image_filter.model.11.conv_block.5.bias", "image_filter.model.12.conv_block.1.bias", "image_filter.model.12.conv_block.5.bias", "image_filter.model.13.conv_block.1.bias", "image_filter.model.13.conv_block.5.bias", "image_filter.model.14.conv_block.1.bias", "image_filter.model.14.conv_block.5.bias", "image_filter.model.15.conv_block.1.bias", "image_filter.model.15.conv_block.5.bias".

**Comment by troylujc** [comment]
I figured it out. It is caused by the torch version differences between training and evaluating time.

**Comment by jiandandian2** [comment]
> I figured it out. It is caused by the torch version differences between training and evaluating time.

I have the same problem, both my train and test are under the same environment.

**Comment by troylujc** [comment]
> > I figured it out. It is caused by the torch version differences between training and evaluating time.
> 
> I have the same problem, both my train and test are under the same environment.

Maybe you can try the following code in eval.py line 49
netC.load_state_dict(torch.load(opt.load_netC_checkpoint_path, map_location=cuda), strict=False)

**Comment by jiandandian2** [comment]
it works! but the output seems not good
<img width="2032" alt="屏幕快照 2020-08-09 上午10 20 04" src="https://user-images.githubusercontent.com/33227739/89723534-56534200-da2a-11ea-9b62-8f799606438d.png">

**Comment by shunsukesaito** [comment]
Did you train with the single scan file as the example? I wouldn't expect it to be generalized well. For better generalization, please consider using larger scale dataset.

**Comment by jiandandian2** [comment]
> Did you train with the single scan file as the example? I wouldn't expect it to be generalized well. For better generalization, please consider using larger scale dataset.

yes, I'll try

**Comment by troylujc** [comment]
> it works! but the output seems not good
> <img alt="屏幕快照 2020-08-09 上午10 20 04" width="2000" src="https://user-images.githubusercontent.com/33227739/89723534-56534200-da2a-11ea-9b62-8f799606438d.png">

If you trained the color net following the Readme guidence without adding norm_color option, it will use batch normalization rather than group normalization. So when you test it, you need to delete '--norm_color group' in test.sh, or your test network will be not compatible with the trained model (Error(s) in loading state_dict). Simply adding strict=False may lead to a bad output!
