### ISSUE TITLE
How to process Buff dataset?

### ISSUE THREAD

**Issue by tau-yihouxiang** [shunsukesaito/PIFu#63]
I am struggling with processing the .ply format data on Buff dataset. I don't know how to convert .ply file to .obj file with texture images. Could you share some clue? Thank you in advance!

**Comment by tau-yihouxiang** [comment]
Could you help me to solve the problem? @shunsukesaito

**Comment by shunsukesaito** [comment]
You don't need to convert ply files into texture images. Instead, you can modify the rendering code to load color from vertices as BUFF data has color per vertex.
