### ISSUE TITLE
About Training Datas

### ISSUE THREAD

**Issue by pursur** [shunsukesaito/PIFu#65]
Hello,Thanks vary much to release codes about PIFu，which provide some help for my studying.However,it takes place a error which the netC model can not load some datas from pre-traing model file.`(netC.load_state_dict(torch.load(opt.load_netC_checkpoint_path, map_location=cuda),strict=False))`. Furtherly, I want to train this model,where can   this dataset of the model be found .
Thanks vary much again.
Best regards.

**Comment by shunsukesaito** [comment]
For color model, please refer to #61 and #58 for the solution. The model is trained with commercial scans as we mentioned in the technical paper. You can either purchase the same data (but it's expensive) or seek publicly available dataset.
