### ISSUE TITLE
cannot import 'Textures'

### ISSUE THREAD

**Issue by Dominoer** [shunsukesaito/PIFu#66]
```
/content/PIFu/lib/colab_util.py in <module>()
     16 
     17 # Data structures and functions for rendering
---> 18 from pytorch3d.structures import Meshes, Textures
     19 from pytorch3d.renderer import (
     20     look_at_view_transform,

ImportError: cannot import name 'Textures'
```
Thanks for your excellent work. When I using your colab demo, it gives me the above error. Could you please tell me how to fix the error? Sorry for the dumb question. I searched for it but nothing helps.

**Comment by Dominoer** [comment]
It seems like the Pytorch3d team has changed the basic file.

**Comment by Dominoer** [comment]
I have fixed the error by changing _from pytorch3d.structures import Textures_ to _from pytorch3d.renderer.mesh import Textures_. But it may not be a permanent solution. It would be appreciated if you could modify your original colab_utils file.

**Comment by Dominoer** [comment]
Sorry for bothering you! I have fixed the problem perfectly by changing _from pytorch3d.structures import Textures_ to `from pytorch3d.renderer import TexturesVertex`, and `textures = TexturesVertex(verts_features=verts_rgb_colors)`. 
Closed!

**Comment by suyashjoshi** [comment]
@Dominoer did you submit a PR and was it merged?

**Comment by suyashjoshi** [comment]
thanks for the fix btw

**Comment by suyashjoshi** [comment]
after making the suggested changes I'm getting this error:

```
/content/pifuhd/lib/colab_util.py in <module>()
     41 from pytorch3d.renderer import TexturesVertex
     42 from pytorch3d.structures import Meshes
---> 43 from pytorch3d.renderer import (
     44     look_at_view_transform,
     45     OpenGLOrthographicCameras,

ImportError: cannot import name 'TexturedSoftPhongShader'

```

**Comment by Dominoer** [comment]
The merged version has addressed the issue, please clone the newest version.
