### ISSUE TITLE
prt_util weird code

### ISSUE THREAD

**Issue by sxyu** [shunsukesaito/PIFu#69]
Hi Shunsuke,

I've been reading `apps/prt_util.py`. Please point out if I am understanding incorrectly, but I feel this code is very strange:
```python
def computePRT(mesh_path, n, order):
    vectors, phi, theta = sampleSphericalDirections(n)
    SH = getSHCoeffs(order, phi, theta)
    ...
    for i in tqdm(range(n)):
        SH = np.repeat(SH[None,(i*n):((i+1)*n)], n_v, axis=0).reshape(-1,SH.shape[1])
        vectors = np.repeat(vectors[None,(i*n):((i+1)*n)], n_v, axis=0).reshape(-1,3)
```
For `i>0`, doesn't all SH and vectors get overwritten (and use the previous value) rather than a random one? So it is only using 40 directions rather than 40*40..

Thanks,
Alex

**Comment by shunsukesaito** [comment]
Thanks for the fix!! Yes it is the bug and potentially degraded the accuracy of PRT reconstruction.
