### ISSUE TITLE
Query regarding computing Chamfer loss

### ISSUE THREAD

**Issue by jsaisagar** [shunsukesaito/PIFu#7]
Dear Shunsukesaito,

Nice work. Thanks for releasing the code.
May I know how to compute chamfer loss on the output meshes w.r.t ground truth meshes? As both the meshes will be in different coordinate systems.

Thanks,

**Comment by shunsukesaito** [comment]
In case you have ground truth mesh, you should have access to transformation matrix from model space to camera space. We simply apply the inverse of transformation matrix to place the reconstruction in the same coordinate system first. Then we uniformly sample 10k points on the target and reconstruction meshes using trimesh's sample_surface_even, which is used by chamfer distance computation.

**Comment by zhangyahu1** [comment]
Is the alignment needed betwenn GT mesh and estiamted mesh when calculating the metrics? Thanks!
