### ISSUE TITLE
z-feature for perspective camera model

### ISSUE THREAD

**Issue by yangze0930** [shunsukesaito/PIFu#73]
Hi Shunsuke, 

thanks for your great work. If I want to train the model with perspective camera model, what do you think is a good z-feature? I have tried to use the z-feature as the depth of human pelvis minus the depth of sample point in camera coordinate system, in this way we ensure the pelvis centers are aligned across data sample, but the result is still not good enough compared to using orthographic camera model. As shown in the attached image, it struggles at figuring out depth at foot. Do you have some suggestions? Thanks for your reply!

Best,
Ze

![Screen Shot 2020-09-16 at 9 50 04 PM](https://user-images.githubusercontent.com/17019659/93410232-9a760580-f866-11ea-8b49-f7cf290fe5bb.png)
![Screen Shot 2020-09-16 at 9 49 55 PM](https://user-images.githubusercontent.com/17019659/93410235-9ba73280-f866-11ea-8f1c-f85a8c8d049a.png)

**Comment by yangze0930** [comment]
additional information

**Comment by shunsukesaito** [comment]
As you mentioned, probably simply normalizing depth by pelvis does not fully resolve the problem. There are recent followup works that attempt to address the issue. You can probably check them out.
https://arxiv.org/abs/2006.08072
https://arxiv.org/abs/2007.03858
https://arxiv.org/abs/2004.04572

**Comment by yangze0930** [comment]
Hi @shunsukesaito, thanks for your reference.
