### ISSUE TITLE
Question about projection matrices

### ISSUE THREAD

**Issue by nvdomidi** [shunsukesaito/PIFu#75]
Hello shunsukesaito,

After reading the code thoroughly I noticed the way you go from 3D points to 2D points is by the use of a matrix named "calibs", and in the training process this matrix is formed by the multiplication of an instrinsic camera matrix by an extrinsic matrix.

But the way you create the intrinsic matrix in `TrainDataset.py line 160` is different from my understanding of camera intrinsic matrices.

Can you please explain _why_  this matrix does the camera space to image pixel space matching?

In particular I cant understand what the `scale` and `ortho_ratio` parameters are and why they are chosen this way.

In `render_data.py`: 

`y_scale = 180/(vmax[up_axis] - vmin[up_axis])` : this is equivalent to scale
`cam.ortho_ratio = 0.4 * (512 / im_size)` : and this is ortho_ratio

I apologize if this question is very specific on the details. Im reading about multiview geometry from multiple resources and I cant understand what your implementation is doing in theory.

Thanks in advance!

**Comment by shunsukesaito** [comment]
The values are set so that every subjects in the training data has the same height. As the camera is weak-perspective (scaled orthogonal), it does not have focal length or principal points like a perspective camera model.
