### ISSUE TITLE
OpenGL.error(s)

### ISSUE THREAD

**Issue by ckxz** [shunsukesaito/PIFu#76]
Hi @shunsukesaito,
I'm currently facing a problem previously reported (and supposedly solved) in issue #16.
Running render_data.py on macOS (no GPU) yields a GLError because loadShader fails to compile any shader:

<img width="1335" alt="imatge" src="https://user-images.githubusercontent.com/44316878/93987935-73e52c80-fd88-11ea-8f85-a501c429b074.png">

If I run the same script on a Win64 (with GPU) a different error is raised:

<img width="1335" alt="OpenGL error on Windows" src="https://user-images.githubusercontent.com/44316878/93988412-f66dec00-fd88-11ea-93ec-9845ea8ed237.png">

Are these errors related only to the OS? I have no access to a Linux machine. I'd really appreciate if you could give me a hand solving this. 
Keep up the awesome work.

**Comment by ckxz** [comment]
Hi @electronicliujiang, 
Could you please share how was your problem discussed in #16 dealt with? What operating system were you working on? Beyond my efforts to make it run on macOS and Windows, I am getting headless rendering related errors (**freeglut (foo): failed to open display ''**) when running it on colab (Linux kernel).
Would really appreciate your help!

**Comment by ckxz** [comment]
Running it on a Linux machine (with **libosmesa6-dev** and **freeglut3-dev** installed) did the work.

**Comment by bluestyle97** [comment]
I meet this problem on a Linux machine on which `libosmesa6-dev` and `freeglut3-dev` have been properly installed. Finally I solve it by `export MESA_GL_VERSION_OVERRIDE=3.3` before running `render_data.py`.
