### ISSUE TITLE
Define watertight mesh

### ISSUE THREAD

**Issue by ckxz** [shunsukesaito/PIFu#79]
I'm trying to implement the PIFu framework with my own dataset and wonder what is the understanding of watertight meshes in this context. 

Do all/any of the following requirements apply to it?
- No non-manifold vertices
- No non-manifold edges 
- No self-intersections

Or do you simply understand a watertight mesh as one that simply has no holes in its surface?

Thanks for the great work. Keep it up!

**Comment by shunsukesaito** [comment]
It depends on an algorithm for occupancy checking. The conditions you mentioned above may result in inaccurate occupancy labels for training in embree the code base is currently using. You could instead use robust occupancy detection algorithms such as generalized winding numbers (https://igl.ethz.ch/projects/winding-number/).
