### ISSUE TITLE
 How to train model in the case of having Buff dataset

### ISSUE THREAD

**Issue by pursur** [shunsukesaito/PIFu#80]
Hi, I am very interested in your research, especially this code about PiFu model. I have gotten the Buff dataset now. How isThe Buff dataset  integrated your code in the TrainDataset.py file? 
In additional, how are the point-to-surface Euclidean distance P2S , the Chamfer distance and the normal reprojection error calculated. what their formulas are.

**Comment by shunsukesaito** [comment]
You have to modify the code to incorporate BUFF dataset in the training. To do so, you have to first render BUFF dataset by modifying the released rendering code and somehow fix holes in the mesh (note that BUFF meshes are not watertight but PIFu training requires watertight mesh for ground-truth occupancy labels.)
Regarding evaluation, you can look at the previous issue here.
https://github.com/shunsukesaito/PIFu/issues/56
