### ISSUE TITLE
test question

### ISSUE THREAD

**Issue by jiandandian2** [shunsukesaito/PIFu#81]
hello, your work is very impressed and i want to know the what is the difference between eval_grid_octree and eval_grid,  in the sdf.py
![image](https://user-images.githubusercontent.com/33227739/95753811-b9847d80-0cd4-11eb-8e44-29c1cac53de1.png)

**Comment by shunsukesaito** [comment]
eval_grid evaluates the entire 3d space, which might be extremely slow for high-resolution. eval_grid_octree hierarchically determines which grids need to be evaluated, thus accelerating the reconstruction time. Unless you have specific reason, I would recommend using eval_grid_octree all the time. Our follow-up work (https://github.com/Project-Splinter/MonoPort) has even more sophisticated faster reconstruction algorithm.

**Comment by jiandandian2** [comment]
> eval_grid evaluates the entire 3d space, which might be extremely slow for high-resolution. eval_grid_octree hierarchically determines which grids need to be evaluated, thus accelerating the reconstruction time. Unless you have specific reason, I would recommend using eval_grid_octree all the time. Our follow-up work (https://github.com/Project-Splinter/MonoPort) has even more sophisticated faster reconstruction algorithm.

thanks for your answer
