### ISSUE TITLE
Training with Real Images Captured by Camera

### ISSUE THREAD

**Issue by 475651582** [shunsukesaito/PIFu#83]
Hi, 
thanks for your code! It's really a great work!
I am training PIFu with images that captured by camera and I change the _projection mode_ to 'perspective'.
However, I found the speed of convergence is much slower than orthogonal mode. Does it make sense?
Thank you in advance!

**Comment by shunsukesaito** [comment]
Generally speaking, depth normalization is the key to stably train PIFu. For orthogonal, this can be easily achieved as depth center can be arbitrarily set. However, for perspective, you need to be careful about depth range each data sample takes. If they are not well normalized, convergence can be extremely slow.
