### ISSUE TITLE
Renderable Dataset

### ISSUE THREAD

**Issue by wangfudong** [shunsukesaito/PIFu#89]
Hi,
Recently, I have tried to re-train the network. Since the RenderPeople/AXYZ datas are too expensive for me, I used the dataset with 96 3D bodies from the paper "Multi-Garment Net: Learning to Dress 3D People from Images, ICCV'19" (https://github.com/bharat-b7/MultiGarmentNetwork). However,  its quality is not good enough (e.g., the faces are blurred due to personal privacy) so that the recontruction results are somehow poor. 

I have reviewd some recent works that released useful 3D boody datas, including Human3.6M, SURREAL, 3DPW, 3Dpeople, THUman, Multi-Garment, BUFF, DFaust, NBA2K, SIZER, etc. However, only a few of them have both geometry models and texture images, or colored point-cloud datas, like  Multi-Garment, NBA2K, SIZER. And some data preprocessing steps are also need to prepare for the renderable model.

Would you share some experices on:
1. Are there some other 3D human datasets can be used for renderring the trainning datas?
2. How much do you pay to buy the RenderPeople datas? Is there a discount for research usage?

Than you so much~

**Comment by shunsukesaito** [comment]
>Are there some other 3D human datasets can be used for renderring the trainning datas?

I think the datasets you listed above is pretty complete if I don't miss any. 

>How much do you pay to buy the RenderPeople datas? Is there a discount for research usage?

If I remember correctly, it was around 10k USD (yes it's expensive...). Regarding a potential discount, please directly reach out to RenderPeople to get invoice.
