### ISSUE TITLE
HDRI background

### ISSUE THREAD

**Issue by pourzs** [shunsukesaito/PIFu#9]
Hi, I was wondering how can I add hdri background to the rendered images, as was described in the paper?

**Comment by shunsukesaito** [comment]
I'm not sure which part of paper you are referring to. While we didn't add HDRI background to render images, we use HDRI images to create a set of 2nd order spherical harmonics (please find env_sh.npy in the repo) and use them to render RenderPeople data using precomputed radiance transfer. For detail, please refer to the README and the paper.

**Comment by LogWell** [comment]
For `we use HDRI images to create a set of 2nd order spherical harmonics`, is there any material for reference?
