### ISSUE TITLE
single part C is useful？

### ISSUE THREAD

**Issue by chensjtu** [shunsukesaito/PIFu#91]
Dear Author: Hello! Thank you for your outstanding contribution to the open source community, and I've been reading your great work recently. I'd like to know how to take out your NETC alone as a Colorer for other parametric models.
In other words, I use other networks to reconstruct the 3D model, and Pifu will not participate in the establishment of this model. Is it feasible to simply use Pifu as the Colorer of the 3D model?
If possible, what relevant parts may I need to modify?
BTW, I've noticed
netC.attach ( netG.get_ Im_ feat())
Can cfeat achieve my goal by preparing ahead of time?

**Comment by shunsukesaito** [comment]
So the issue with not taking geometry part is the following color module has no idea what the underlying 3D geometry is. Thus, it's not possible to fill in the color of missing regions. 

One thing you could try is to optimize image feature of netG by fixing MLP such that occupancy prediction of MLP matches that of the given 3D shape. Once the optimization is finished, you can attach the optimized image feature to netC. This way, you could still provide 3D geometry information to the color module in a consistent manner. (But I don't guarantee that this would work as I have never tried it out.)
