### ISSUE TITLE
Tensor size mis-match error when input is not 512x512

### ISSUE THREAD

**Issue by tianli** [shunsukesaito/PIFu#92]
Hi, I got an error in [here](https://github.com/shunsukesaito/PIFu/blob/975331106479436356fe8fae9ca2b96a56926930/lib/train_util.py#L79)

torch.Size([1, 256, 220, 128])
torch.Size([1, 256, 221, 128])
error: ('Sizes of tensors must match except in dimension 2. Got 221 and 220 (The offending index is 0)',)

Seems that the tensor size does not match. My input image and mask are of size 1356 x 2336.

Thanks!

**Comment by shunsukesaito** [comment]
Please be aware that there's 4 downsampling operations in our stacked hourglass network. This means your input image should be divisible by 16 for each dimension. Looks like your input doesn't satisfy this condition.
