### ISSUE TITLE
Watertight mesh issue

### ISSUE THREAD

**Issue by RohanChacko** [shunsukesaito/PIFu#93]
Hi,

May I know at what part of the code would the non-watertightness of meshes cause an issue for training/inference?

**Comment by GTO2013** [comment]
It will cause issues when you sample the meshes in the TrainDataset selectSamplingMethod. You will get incorrect SDF sample values. I can recommend the mesh_to_sdf package, it uses the DeepSDF approach of virtual cameras to create sdf samples. This works better on non-watertight meshes, like in ShapeNET.
