### ISSUE TITLE
DataParallel not called for model init

### ISSUE THREAD

**Issue by RohanChacko** [shunsukesaito/PIFu#94]
Hi,

I noticed that HGPIFuNet isn't actually using multi-gpus. The model returned from [init_net](https://github.com/shunsukesaito/PIFu/blob/master/lib/net_util.py#L254) fn is not returned to anything when called [here](https://github.com/shunsukesaito/PIFu/blob/master/lib/model/HGPIFuNet.py#L55). Same is the case for ResBlkPIFuNet [here](https://github.com/shunsukesaito/PIFu/blob/master/lib/model/ResBlkPIFuNet.py#L37). The initialized model runs only one gpu as shown [here](https://github.com/shunsukesaito/PIFu/blob/master/apps/train_shape.py#L50). 

Please let me know if I'm missing out on something.

**Comment by shunsukesaito** [comment]
Yes, the current code base doesn't support muliti-GPUs and I don't plan to add it myself at this moment (pull request is always welcome though.)
