### ISSUE TITLE
Using Real Images for inference

### ISSUE THREAD

**Issue by tejokrishna** [shunsukesaito/PIFu#95]
Hi Shunsuke,
 
     Thanks for sharing the code and the weights. I have a quick question, I am trying to use real world pictures which have perspective projection. Using the intrinsics, I saw that we can set the calib tensor. Is there an example that I can take a look at? Using the projection mode set to perspective is yielding bad results. Thanks in anticipation.

**Comment by shunsukesaito** [comment]
The released model is trained with weak-perspective projection and I don't expect it to perform well when changing it to perspective during inference. One thing you could try is to approximate perspective by weak perspective projection for PIFu inference and convert it back the original space after 3D reconstruction. Check out the following code for reference. 

https://github.com/nkolot/SPIN/blob/5c796852ca7ca7373e104e8489aa5864323fbf84/train/trainer.py#L162

**Comment by tejokrishna** [comment]
Thank you Shusuke, that link is quite helpful.

**Comment by ChanYeongShin** [comment]
@tejokrishna Did you implement PIFu by using real images for inference? If you've done, can you share the code..? Thank you.
